// Generated by CoffeeScript 1.6.2
var changeTitle, main, onInputChange;

changeTitle = function(ev) {
  return ev.tartget.value;
};

onInputChange = function(header) {
  return function(ev) {
    return header.innerText = ev.target.value;
  };
};

main = function() {
  var header, input;

  header = document.querySelector('h1');
  header.innerText = 'NASER SI!';
  input = document.createElement('input');
  document.body.appendChild(input);
  return input.addEventListener('keyup', onInputChange(header), false);
};

window.addEventListener('load', main, false);
