// Generated by CoffeeScript 1.6.2
var main;

main = function() {
  var commentAddForm;

  chrome.runtime.sendMessage({
    type: 'comments'
  }, function(response) {
    var commentList;

    commentList = $('#comments-list');
    return $.each(response, function(index, item) {
      return commentList.append("<tr><td>" + item.date + "</td><td>" + item.content + "</td><td>" + item.content + "</td><td>" + item.nick + "</td></tr>");
    });
  });
  commentAddForm = $('form#comments-add-form');
  return commentAddForm.submit(function() {
    alert(commentAddForm.serializeArray());
    return false;
  });
};

document.addEventListener('DOMContentLoaded', main, false);
