// Generated by CoffeeScript 1.6.2
var loadComments;

loadComments = function() {
  console.log('load');
  return chrome.runtime.sendMessage({
    type: 'comments'
  }, function(response) {
    var commentList;

    commentList = $('#comments_list');
    return $.each(response, function(index, item) {
      return commentList.append("<tr><td>" + item.date + "</td><td>" + item.content + "</td><td>" + item.content + "</td><td>" + item.nick + "</td></tr>");
    });
  });
};

document.addEventListener('DOMContentLoaded', loadComments, false);
