// Generated by CoffeeScript 1.6.2
var loadComments, renderComments, sendComment;

sendComment = function() {
  var dataSource;

  console.log("click");
  dataSource = $("#comment_area");
  return chrome.tabs.query({
    active: true,
    currentWindow: true
  }, function(tabs) {
    var request;

    console.log(dataSource);
    request = {
      type: 'create-comment',
      data: {
        uri: tabs.length ? tabs[0].url : void 0,
        channel: '838b612f-2f22-4d6f-a214-0da2f69a5c9c',
        message: dataSource.val()
      }
    };
    return chrome.runtime.sendMessage(request, function(response) {
      return console.log(response);
    });
  });
};

renderComments = function(data) {
  var commentList;

  commentList = $('#comments-list');
  return $.each(data, function(index, item) {
    return commentList.append("<tr><td>" + item.date + "</td><td>" + item.message + "</td><!--td>" + item.content + "</td><td>" + item.nick + "</td--></tr>");
  });
};

chrome.runtime.onMessage.addListener(function(message, sender, response) {
  if (message.type === 'search-result') {
    return renderComments(message.data);
  }
});

loadComments = function() {
  var button;

  button = $("#send_button");
  button.click(sendComment);
  return chrome.runtime.sendMessage({
    type: 'comments'
  }, function(response) {
    return false;
  });
};

document.addEventListener('DOMContentLoaded', loadComments, false);
