// Generated by CoffeeScript 1.6.1
var getLocation, handleURLChange, ws, _sample_comments;

ws = io.connect('http://localhost:8000');

getLocation = function(url) {
  var a;
  a = document.createElement('a');
  a.href = url;
  return a;
};

handleURLChange = function(tabId, changeInfo, tab) {
  var link, _ref;
  if (changeInfo.status === 'complete') {
    link = getLocation(tab.url);
    if ((_ref = link.protocol) === 'http:' || _ref === 'https:') {
      chrome.pageAction.show(tabId);
      return chrome.pageAction.onClicked.addListener(function(tab) {
        return chrome.pageAction.setPopup({
          tabId: tabId,
          popup: 'page_content/popup.html'
        });
      });
    }
  }
};

_sample_comments = [
  {
    "type": "comment",
    "date": "1.4.2013",
    "content": "První comment",
    "nick": "A",
    "uid": "4Rx4RNk1UX7Dvq"
  }, {
    "type": "comment",
    "date": "1.4.2013",
    "content": "2. komentář",
    "nick": "B",
    "uid": "4Rx4RNk1UX7Dvq"
  }, {
    "type": "comment",
    "date": "1.4.2013",
    "content": "Další příspěvek",
    "nick": "C",
    "uid": "99wFJ0B"
  }
];

chrome.tabs.onUpdated.addListener(handleURLChange);

chrome.runtime.onMessage.addListener(function(message, sender, response) {
  if ((message != null ? message.type : void 0) == null) {
    return false;
  }
  switch (message.type) {
    case 'create-comment':
      ws.emit('publish', message.data);
      break;
    case 'comments':
      chrome.tabs.query({
        active: true,
        currentWindow: true
      }, function(tabs) {
        if (tabs.length) {
          return ws.emit('search', tabs[0].url);
        }
      });
      break;
    case 'url':
      chrome.tabs.query({
        active: true,
        currentWindow: true
      }, function(tabs) {
        if (tabs.length) {
          return response({
            url: tabs[0].url
          });
        }
      });
      break;
    default:
      console.log("Unknown type '" + message.type + "'");
      return false;
  }
  return true;
});

ws.on('channel-created', function(data) {
  return console.log(data);
});

ws.on('search-result', function(data) {
  var message;
  console.log(data);
  message = {
    type: 'search-result',
    data: data
  };
  console.log('a');
  return chrome.runtime.sendMessage(message, function(response) {
    return false;
  });
});
