// Generated by CoffeeScript 1.6.2
var getLocation, handleURLChange;

getLocation = function(url) {
  var a;

  a = document.createElement('a');
  a.href = url;
  return a;
};

handleURLChange = function(tabId, changeInfo, tab) {
  var link, _ref;

  if (changeInfo.status === 'complete') {
    link = getLocation(tab.url);
    if ((_ref = link.protocol) === 'http:' || _ref === 'https:') {
      chrome.pageAction.show(tabId);
      return chrome.pageAction.onClicked.addListener(function(tab) {
        return chrome.pageAction.setPopup({
          tabId: tabId,
          popup: 'page_content/popup.html'
        });
      });
    }
  }
};

chrome.tabs.onUpdated.addListener(handleURLChange);

chrome.runtime.onMessage.addListener(function(message, sender, response) {
  if (((message != null ? message.get : void 0) != null) && message.get === 'url') {
    chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs) {
      if (tabs.length) {
        return response({
          url: tabs[0].url
        });
      }
    });
    return true;
  }
});
